image: pulumi/pulumi-nodejs:latest

definitions:
  steps:
    - step:
        name: Restore npm dependencies
        script:
          - &deps |
            export PULUMI_STACK_NAME={{ .PulumiStackName }}
            export PULUMI_WORKING_DIRECTORY={{ .WorkingDirectory }}
            yarn install --cwd ${PULUMI_WORKING_DIRECTORY}
pipelines:
  pull-requests:
    - step:
        name: Preview update to infrastructure
        script:
          - *deps
          - pulumi preview --cwd ${PULUMI_WORKING_DIRECTORY} -s ${PULUMI_STACK_NAME}
  
  branches:
    master:
      - step:
          name: Update infrastructure
          # Using the deployment keyword will ensure that only one pipeline is executing for
          # the deployment environment at any given time.
          deployment: {{ .PulumiStackName }}
          script:
            - *deps
            - pulumi up --yes --cwd ${PULUMI_WORKING_DIRECTORY} -s ${PULUMI_STACK_NAME}
