name: Preview or update Pulumi app {{ pulumiStackName }}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PULUMI_STACK_NAME: {{ pulumiStackName }}
  {{ cloudProviderSecrets }}

jobs:
  buildSite:
    env:
      GOPATH: ${{ github.workspace }}
    name: Install deps and build site
    runs-on: ubuntu-latest
    steps:

      # Turnstyle is used to prevent multiple push jobs from running at the same time. We
      # limit it to push jobs to allow PR jobs to run concurrently.
      - name: Turnstyle
        if: ${{ github.event_name == 'push' }}
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Add GOBIN to PATH
        run: echo "::add-path::$(go env GOPATH)/bin"

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@releases/v1

      - name: PR previews
        run: pulumi preview -s $PULUMI_STACK_NAME
        if: ${{ github.event_name == 'pull_request' }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          {{ cloudProviderSecrets }}

      - name: Apply infrastructure update
        run: pulumi update --yes -s $PULUMI_STACK_NAME
        if: ${{ github.event_name == 'push' }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          {{ cloudProviderSecrets }}
